Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;

namespace Restaurant.Controllers
{
    public class AdminController : Controller
    {
        private readonly ModelContext _context;
        public AdminController (ModelContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.numberOfCustomers = _context.Customers.Count();
            ViewBag.Sale=_context.Products.Sum(x => x.Sale);
            ViewBag.MinPrice = _context.Products.Min(x => x.Price); 
            ViewBag.MaxPrice = _context.Products.Max(x => x.Price); 
            ViewBag.Customer = _context.Customers.ToList();
            return View();
        }
    }
}

Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurant.Models;

namespace Restaurant.Controllers
{
    public class AuthController : Controller
    {
        private readonly ModelContext _context;

        private readonly IWebHostEnvironment _hostEnvironment;
        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        

        public AuthController (ModelContext context,
        IWebHostEnvironment _hostEnvironment)

        {

            this._hostEnvironment = _hostEnvironment;

            _context = context;

        }
        [HttpPost]

        [ValidateAntiForgeryToken]

        public async Task<IActionResult>
        Register([Bind("Id,Fname,Lname,Imagepath,ImageFile")] Customer customer, string username, string password)
        {

            if (ModelState.IsValid)

            {

                string wwwRootPath = _hostEnvironment.WebRootPath;

                string fileName = Guid.NewGuid().ToString() + "_" + customer.ImageFile.FileName;
                string extension = Path.GetExtension(customer.ImageFile.FileName);

                customer.ImagePath = fileName;

                _context.Add(customer);

                await _context.SaveChangesAsync();

                UserLogin login = new Models.UserLogin();

                login.RoleId = 1;

                login.Passwordd = password;

                login.UserName = username;

                login.CustomerId = customer.Id;

                _context.Add(login);

                await _context.SaveChangesAsync();
                return RedirectToAction("Login", "AuthController");

            }

            return View(customer);
        }

    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Restaurant.Models;

namespace Restaurant.Controllers
{
    public class HomeController : Controller
    {
        private readonly ModelContext _context;
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger, ModelContext context)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var categories =_context.Categoories.ToList();
            return View(categories);

        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet("Home/GetProductByCategory/{id}")]
        public IActionResult GetProductByCategory(int id)
        {
            var products = _context.Products.Where(x => x.CategoryId == id).ToList();
            return View("GetProductByCategory", products);
        }

    }
}

Views/Home/GetProductByCategory.cshtml
@{
    Layout = "_Resto";
}
<head>
    <title> Products...</title>
</head>
<body>
    <div class="container mt-4">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-6 col-md-4 col-lg-3">
                    <div class="card">
                        <img src="@Url.Content("~/AdminAssets/img/" + item.Namee + ".jpg")" class="card-img-top" alt="Food Image" width="200" height="300">
                        <div class="card-body">
                            
                            <h5 class="card-title">Name: @item.Namee</h5>
                            <p class="card-text"> Price: @item.Price</p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</body>

Views/Home/Index.cshtml
@model IEnumerable<Categoory>
@{
    Layout = "_Resto";
}
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation
        ==========================================-->
    <nav id="menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#features" class="page-scroll">Specials</a></li>
                    <li><a href="#about" class="page-scroll">About</a></li>
                    <li><a href="#restaurant-menu" class="page-scroll">Menu</a></li>
                    <li><a href="#contact" class="page-scroll">Contact</a></li>
                    <li><a href="@Url.Action("Register", "Auth")" class="page-scroll">Register</a></li>
                    <li><a href="@Url.Action("Index", "Admin")" class="page-scroll">Admin Dashboard</a></li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
    </nav>
    <!-- Header -->
    <header id="header">
        <div class="intro">
            <div class="overlay">
                <div class="container">
                    <div class="row">
                        <div class="intro-text">
                            <h1>Twist & Taste </h1>
                            <p>Reservations: (+962) 785964882</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Features Section -->
    <div id="features" class="text-center">
        <div class="container">
            <div class="section-title">
                <h2>Our Specials</h2>
            </div>
                @foreach (var item in Model)
                {
                    <div class="col-sm-6 col-lg-4">
                        <div class="single_blog_item">
                            <div class="single_blog_img">
                                <img width="330" height="330" src="@Url.Content("~/images/"+item.ImagePath)" alt="">
                            </div>
                            <div class="single_blog_text">
                                <h3>@item.CategoryName</h3>
                                <p> Was brean shed moveth day yielding tree yielding day were female and </p>
                                <a asp-action="GetProductByCategory" asp-route-id="@item.Id" class="btn_3"> View Products </a>
                            </div>
                        </div>
                    </div>
                }
        </div>
    </div>
    <!-- About Section -->
    <div id="about">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12 col-md-6 about-img"> </div>
                <div class="col-xs-12 col-md-3 col-md-offset-1">
                    <div class="about-text">
                        <div class="section-title">
                            <h2>Our Story</h2>
                        </div>
                        <p> Twist & Taste </p>
                        <p>Where every bite tells a story, and every twist brings a new flavor to savor. Duis sed dapibus leo nec ornare.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Restaurant Menu Section -->
    <div id="restaurant-menu">
        <div class="container">
            <div class="section-title text-center">
                <h2>Menu</h2>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="menu-section">
                        <h2 class="menu-section-title">Breakfast & Starters</h2>
                        <div class="menu-item">
                            <div class="menu-item-name">Tortellini Skewers</div>
                            <div class="menu-item-price"> $9 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Fried Ravioli</div>
                            <div class="menu-item-price"> $7 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Wild Mushroom Arancini</div>
                            <div class="menu-item-price"> $9 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Mozzarella Sticks</div>
                            <div class="menu-item-price"> $10 </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="menu-section">
                        <h2 class="menu-section-title">Main Course</h2>
                        <div class="menu-item">
                            <div class="menu-item-name">Mandi</div>
                            <div class="menu-item-price"> $30 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Chicken & Mushroom Pasta</div>
                            <div class="menu-item-price"> $20 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Fish</div>
                            <div class="menu-item-price"> $14 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Chicken Goujons</div>
                            <div class="menu-item-price"> $19 </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <div class="menu-section">
                        <h2 class="menu-section-title">Dinner</h2>
                        <div class="menu-item">
                            <div class="menu-item-name">Pizza</div>
                            <div class="menu-item-price"> $15 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Chicken & Vegetables</div>
                            <div class="menu-item-price"> $17 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">asta Salad</div>
                            <div class="menu-item-price"> $18 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Egg & Avocado Salad</div>
                            <div class="menu-item-price"> $20 </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6">
                    <div class="menu-section">
                        <h2 class="menu-section-title">Desserts</h2>
                        <div class="menu-item">
                            <div class="menu-item-name">Chocolate Mud Cake</div>
                            <div class="menu-item-price"> $11 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Bourbon-Pecan Tart</div>
                            <div class="menu-item-price"> $14 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Texas Sheet Cake</div>
                            <div class="menu-item-price"> $15 </div>
                        </div>
                        <div class="menu-item">
                            <div class="menu-item-name">Vanilla Cheesecake</div>
                            <div class="menu-item-price"> $18 </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Gallery Section -->
    <div id="gallery">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <div class="gallery-item"> <img src="AdminAssets/img/01.jpg" class="img-responsive" alt=""></div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="gallery-item"> <img src="AdminAssets/img/02.jpg" class="img-responsive" alt=""></div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="gallery-item"> <img src="AdminAssets/img/03.jpg" class="img-responsive" alt=""></div>
                </div>
                <div class="col-xs-6 col-md-3">
                    <div class="gallery-item"> <img src="AdminAssets/img/04.jpg" class="img-responsive" alt=""></div>
                </div>
            </div>
        </div>
    </div>


    <!-- Team Section -->
    <div id="team">
        <div class="container">
            <div id="row">
                <div class="col-md-6">
                    <div class="col-md-10 col-md-offset-1">
                        <div class="section-title">
                            <h2>Meet Our Chef</h2>
                        </div>
                        <p>Our Secret Component</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="team-img"><img src="AdminAssets/img/chef.jpg" alt="..."></div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact Section -->
    <div id="contact" class="text-center">
        <div class="container text-center">
            <div class="col-md-4">
                <h3>Reservations</h3>
                <div class="contact-item">
                    <p>Please call</p>
                    <p>(+962) 785964882</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Address</h3>
                <div class="contact-item">
                    <p>Amman Khalda,</p>
                    <p>Dabouq District</p>
                </div>
            </div>
            <div class="col-md-4">
                <h3>Opening Hours</h3>
                <div class="contact-item">
                    <p>Mon-Thurs: 10:00 AM - 11:00 PM</p>
                    <p>Fri-Sun: 11:00 AM - 02:00 AM</p>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="section-title text-center">
                <h3>Send us a message</h3>
            </div>
            <div class="col-md-8 col-md-offset-2">
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text" id="name" class="form-control" placeholder="Name" required="required">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="email" id="email" class="form-control" placeholder="Email" required="required">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div id="success"></div>
                    <button type="submit" class="btn btn-custom btn-lg">Send Message</button>
                </form>
            </div>
        </div>
    </div>


</body>